---
- hosts: localhost
  tasks: 
  - name: VPG Settings Identifier 
    uri: 
      url: "https://192.168.111.20:9669/v1/vpgsettings"
      force_basic_auth: yes
      method: POST
      status_code: 200
      validate_certs: no 
      headers: 
        x-zerto-session: x_zerto_session
        accept: "application/json"
        content-type: "application/json"
      body: "{ }"
      body_format: json
    register: vpgsettings 