---
- hosts: localhost
  tasks: 
  - name: ZVM Login  
    uri: 
      url: "https://192.168.111.20:9669/v1/session/add"
      force_basic_auth: yes
      method: POST
      user: "administrator@vsphere.local"
      password: "Zertodata1!"
      status_code: 200
      validate_certs: no
      body_format: json 
    register: login

